config/routes.rb
Rails.application.routes.draw do
  get "auth/:provider/callback", to: "sessions#google_login"
  get "auth/failure", to: redirect("/")
  get "logout", to: "sessions#logout"

  get "gigs/past", to: "gigs#past"
  resources :gigs do
    resources :links
    resources :posts
  end

  resources :responses
  resources :venues, only: [:index, :show]
  resources :reactions

  get "calendar", to: "calendar#index"
  get "profile", to: "profile#index"

  root "feed#index"
  get "login", to: "login#index"
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :authenticate

  def index
    @gigs = Gig.all
  end
end

app/views/calendar/index.html.erb
<div class="flex items-start justify-between">
  <div>
    <h1 class="text-xl font-bold">Calendar</h1>
  </div>
  <%= link_to new_gig_path, class: "flex items-center font-semibold text-blue-700 dark:text-blue-400 hover:underline" do %>
    <%= heroicon "plus", options: { class: "w-4 h-4" } %>
    Add gig
  <% end %>
</div>

<%= month_calendar(events: @gigs, attribute: :start_date, end_attribute: :end_date) do |date, gigs| %>
  <%= link_to new_gig_path(start_date: date, back: calendar_path), class: "text-xs h-5 w-5 mx-auto flex items-center justify-center rounded-full hover:bg-blue-500#{date == Date.today ? " bg-blue-500" : ""}" do %>
    <%= date.strftime("%e") %>
  <% end %>
  <% gigs.each do |gig| %>
    <%= link_to gig.summary, gig_path(gig.id, back: calendar_path), data: { params: "back=calendar" }, class: "mx-1 text-sm line-clamp-1 font-semibold hover:text-blue-700 dark:hover:text-blue-400" %>
  <% end %>
<% end %>