config/routes.rb
Rails.application.routes.draw do
  get "auth/:provider/callback", to: "sessions#google_login"
  get "auth/failure", to: redirect("/")
  get "logout", to: "sessions#logout"

  get "gigs/past", to: "gigs#past"
  resources :gigs do
    resources :links
    resources :posts
  end

  resources :responses
  resources :venues, only: [:index, :show]
  resources :reactions

  get "calendar", to: "calendar#index"
  get "profile", to: "profile#index"

  root "feed#index"
  get "login", to: "login#index"
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :authenticate
  before_action :set_gig, only: [:create, :update]
  before_action :set_reaction, only: [:update, :destroy]

  def create
    @reaction = Reaction.new(reaction_params)
    @reaction.user = current_user

    if @reaction.save
      redirect_to gig_path(@gig_id)
    end
  end

  def update
    if @reaction.update(reaction_params)
      redirect_to gig_path(@gig_id)
    end
  end

  def destroy
    if @reaction.destroy
      redirect_to gig_path(@reaction.post.gig_id)
    end
  end

  private
    def set_gig
      @gig_id = Post.find(params[:reaction][:post_id]).gig_id
    end

    def set_reaction
      @reaction = Reaction.find(params[:id])
      return unless @reaction.user_id == current_user.id
    end

    def reaction_params
      params.require(:reaction).permit(:emoji, :post_id)
    end
end

app/views/reactions/_form.html.erb
<%= form_with(model: reaction, data: { controller: "emoji-picker", "emoji-picker-target": "form" }) do |form| %>
  <%= form.hidden_field :post_id, value: post.id %>
  <%= form.hidden_field :emoji, "data-emoji-picker-target": "input" %>
  <%= button_tag reaction.id.present? ? reaction.emoji : "React", data: { action: "emoji-picker#toggle", "emoji-picker-target": "button" } %>
<% end %>

app/views/reactions/_list.html.erb
<% reactions.each do |reaction| %>
  <p class="flex items-center justify-between my-1 gap-x-4">
    <span class="text-xs"><%= render 'layouts/user', user: reaction.user %></span>
    <span class="flex items-center gap-x-2">
      <%= sanitize reaction.emoji %>
      <% if reaction.user_id == current_user.id %>
        <%= link_to reaction_path(reaction), "aria-label": "Delete reaction", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this reaction?" }, class: "text-xs" do %>
          <%= heroicon "trash", options: { class: "w-5 h-5" } %>
        <% end %>
      <% end %>
    </span>
  </p>
<% end %>