config/routes.rb
Rails.application.routes.draw do
  get "auth/:provider/callback", to: "sessions#google_login"
  get "auth/failure", to: redirect("/")
  get "logout", to: "sessions#logout"

  get "gigs/past", to: "gigs#past"
  resources :gigs do
    resources :links
    resources :posts
  end

  resources :responses
  resources :venues, only: [:index, :show]
  resources :reactions

  get "calendar", to: "calendar#index"
  get "profile", to: "profile#index"

  root "feed#index"
  get "login", to: "login#index"
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :authenticate

  def index
    @venues = Gig.distinct.pluck(:location).sort
  end

  def show
    @venue = params[:id]
    @gigs = Gig.where(location: params[:id]).where("start_date >= ?", Date.today).order(:start_date)
    @grouped_gigs = @gigs.group_by { |a| a.start_date.strftime("%B %Y") }
    @gigs_by_month = Kaminari.paginate_array(@grouped_gigs, total_count: @grouped_gigs.count).page(params[:page]).per(3)
    @back = params[:back]
  end
end

app/views/venues/index.html.erb
<h1 class="my-6 text-xl font-bold">All venues</h1>
<% if @venues.any? %>
  <ul>
    <% @venues.each do |venue| %>
      <li class="mb-4">
        <%= link_to venue_path(venue.gsub(".", "")) do %>
          <span class="flex items-center text-sm sm:text-md hover:text-blue-700 dark:hover:text-blue-400">
            <%= heroicon "map-pin", variant: :outline, options: { class: "w-5 h-5 mr-l" } %>
            <%= venue %>
          </span>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="text-red-800">No gigs found</p>
<% end %>

app/views/venues/show.html.erb
<%= render 'shared/back_button', label: @back.present? ? "Back" : "Venues", link: @back || venues_path %>
<% if @venue != "Various venues" %>
  <div class="flex flex-col items-center">
    <div class="flex flex-col items-end">
      <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@venue.gsub("&", "and")}&zoom=17&size=800x300&markers=color:red%7C#{@venue}&key=#{ENV["GOOGLE_MAPS_API_KEY"]}", alt: "" %>
      <%= render 'layouts/external_link', link: "http://maps.google.com/?q=#{@venue.split(" ").join("+")}", label: "View in Maps" %>
    </div>
  </div>
<% end %>

<h1 class="my-6 text-xl font-bold">Gigs at <%= @venue %></h1>
<%= render 'gigs/gig_list', gigs_by_month: @gigs_by_month, is_venue: true %>