config/routes.rb
Rails.application.routes.draw do
  get "auth/:provider/callback", to: "sessions#google_login"
  get "auth/failure", to: redirect("/")
  get "logout", to: "sessions#logout"

  get "gigs/past", to: "gigs#past"
  resources :gigs do
    resources :links
    resources :posts
  end

  resources :responses
  resources :venues, only: [:index, :show]
  resources :reactions

  get "calendar", to: "calendar#index"
  get "profile", to: "profile#index"

  root "feed#index"
  get "login", to: "login#index"
end

app/views/layouts/_date_divider.html.erb
<h3 class="flex items-center mb-2">
  <div class="border dark:border-gray-700 w-full mr-2"></div>
  <span class="mx-2 text-xs uppercase text-nowrap"><%= title %></span>
  <div class="border dark:border-gray-700 w-full ml-2"></div>
</h3>

app/views/layouts/_external_link.html.erb
<%= link_to link, target: "_blank", rel: "noopener noreferrer", class: "flex items-center font-semibold text-sm text-blue-700 dark:text-blue-400 hover:underline" do %>
  <%= heroicon "arrow-top-right-on-square", options: { class: "w-4 h-4 mr-1" } %>
  <span class="truncate"><%= label %></span>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="sticky top-0 z-50 flex justify-between px-8 py-3 text-sm bg-blue-400 sm:py-4 sm:text-md dark:bg-blue-600">
  <%= render 'layouts/nav_link', path: root_path, icon: "list-bullet", title: "Feed" %>
  <%= render 'layouts/nav_link', path: gigs_path, icon: "musical-note", title: "Gigs" %>
  <%= render 'layouts/nav_link', path: calendar_path, icon: "calendar-days", title: "Calendar" %>
  <%= render 'layouts/nav_link', path: venues_path, icon: "map-pin", title: "Venues" %>
  <%= render 'layouts/nav_link', path: profile_path, icon: "user-circle", title: "Profile" %>
  <%= render 'layouts/nav_link', path: logout_path, icon: "arrow-right-on-rectangle", title: "Log out" %>
</nav>

app/views/layouts/_nav_link.html.erb
<%= link_to path, class: "flex items-center rounded px-2 py-1 hover:bg-blue-300 dark:hover:bg-blue-700" do %>
  <%= heroicon icon, variant: :mini, options: { class: "w-5 h-5" } %>
  <span class="hidden sm:flex ml-1"><%= title %></span>
<% end %>

app/views/layouts/_user.html.erb
<span class="flex items-center">
  <%= image_tag user.image, alt: "", class: "rounded-full h-6 w-6 mr-1" %>
  <%= user.id == current_user.id ? "You" : user.name %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>BrizGigList</title>
    <meta name="description" content="Information and discussion about gigs in Bristol">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script
      defer
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&loading=async&libraries=places&callback=initMap"
    >
    </script>
  </head>

  <body class="bg-slate-50 text-slate-900 dark:bg-slate-900 dark:text-slate-50">
    <% if current_user.present? %>
      <%= render 'layouts/nav' %>
    <% end %>
    <main class="px-5 mx-auto my-12 lg:mx-32 xl:max-w-screen-lg xl:mx-auto">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
    </main>
  </body>
</html>